### ISSUE TITLE
files in subdirectories can be deployed with incorrect paths on Windows

### ISSUE THREAD

**Issue by XhmikosR** [netlify/netlifyctl#109] opened 2018-04-30 07:07 UTC
I'm on Windows so when I do `netlifyctl deploy ./_site/` the created site doesn't have all the files added recursively thus leading to broken deployment.

**Comment by fool** [comment] 2018-05-03 15:12
The utility does work well on windows for some folks, though it is not heavily tested there.  We're debugging @XhmikosR 's broken deploys in the helpdesk case https://app.intercom.io/a/apps/q245f50x/inbox/inbox/unassigned/conversations/16095351319 (internal link) and will follow up here with our discoveries.

**Comment by calavera** [comment] 2018-05-04 00:31
The issue is here:

https://github.com/netlify/open-api/blob/master/go/porcelain/deploy.go?utf8=%E2%9C%93#L479

We need to replace the back slashes in windows with forward slashes.

**Comment by XhmikosR** [comment] 2018-05-15 10:35
Any news, guys?

**Comment by fool** [comment] 2018-05-21 17:44
blocked on https://github.com/netlify/open-api/issues/86

@XhmikosR  you can already use netlifyctl on Win10 via cygwin or other more capable terminals according to our tests, but we'll try to get this fixed in the next few weeks.

**Comment by MisinformedDNA** [comment] 2018-05-23 11:25
Powershell is a pretty capable terminal, even if the slashes are the other way.

Also, I just tried it on Win 10 Bash shell and it fails there too. Files upload but then are inaccessible.

**Comment by depadiernos** [comment] 2018-05-23 11:29
@MisinformedDNA I've run the Linux version of netlifyctl on Windows 10 WSL and it has worked for me.

**Comment by XhmikosR** [comment] 2018-05-23 11:34
WSL != Windows obviously.

**Comment by XhmikosR** [comment] 2018-05-23 11:35
This is a clearly valid bug, so let's not focus on possible ways to work around it, but rather get it fixed at some point. Otherwise, just state in README that Windows is not supported properly.

**Comment by depadiernos** [comment] 2018-05-23 11:37
Yes, this is definitely a valid bug, which was never in question. Just suggesting a work-around in the meantime.

**Comment by MisinformedDNA** [comment] 2018-05-23 14:51
@depadiernos Here's my scenario:

I am using `wyam` for my static site. Since it's not yet Linux compatible, I can't run the build within Netlify's CD. So now I'm having GitHub trigger a VSTS build. There, I would have to use a Windows build agent, again because of `wyam`, but in my local Windows testing, when I build and upload a ZIP file via the API, the slashes are the wrong way again. Obviously, this was the same issue as with `netlifyctl`.

**Closed** 2018-05-25 17:27 UTC
Labels: bug, low-priority

**Comment by XhmikosR** [comment] 2018-05-29 15:24
Thanks for the fix!
